# Generated by Django 5.2.6 on 2025-09-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_num',
            field=models.IntegerField(),
        ),
    ]
